### PR TITLE
Initial variable implementation

### PR DESCRIPTION
**Pull request by akx**
This PR is the initial implementation of _variables_ for prompts, as discussed in https://github.com/adieyal/dynamicprompts/discussions/61.

# Notes

* The basic syntax is e.g. `${color=red} The sky was ${color} tonight`.
* Variable assignments are (currently) evaluated before any other command in the same sequence; `${color=red} The sky was ${color} tonight ${color=blue}` will yield a blue sky. (This could be changed, but will require us to e.g. split SequenceCommands into sub-sequences on each assignment, and could get hairy.)
* One can nest other commands into the variable assignment's rvalue: `${color={red|blue}}`. 
* By default, the variable holds a reference to the rvalue command as-is, i.e. `${color={red|blue}} ${color} ${color}` in a random sampling context can return two different colors.
* One can force the evaluation of a variable into a literal command immediately with a bang: `${color=!{red|blue}} ${color} ${color}` will then always yield `red red` or `blue blue`.
* There's a shorthand syntax for the common case of setting a simple variable (or multiple) to use in a wildcard reference: `__wildcard(color=red,shape=bouba)__`. This currently _only_ supports literals; you can't use command or other syntax in these. You also can't use a comma or a closing paren in the value.

# Issues (?)

* There is a known issue (marked TODO in the test): `${animal={fox|manatee}} __publicprompts/plush-toy__` will currently **not** generate two plush toys. I've yet to figure out quite why. This could be merged nevertheless...

### CODE REVIEW

**Comment by adieyal** [comment]
Awesome! - I had a brief look. Will test it later this evening.

**Comment by adieyal** [comment]
Just played around with it for a bit. I really think this is a game changer. The holding a reference/immediate evaluation is a nice touch. Two points:

1. We might want to have an option that converts a variable into an empty string if it isn't defined. Right now it throws an error. That's a good thing, but you might want a more forgiving mode
2. It would be really useful if we could have variables in the shorthand syntax. We don't need arbitrary expressions but it would be a shame not to be able to do something like this:
```
${animal={A|B|C}} __publicprompts/plush-toy(animal=${animal})__
```
I know it's effectively the same as:
```
${animal={A|B|C}} __publicprompts/plush-toy__
```
but being able to associate it with the plush-toy template makes the prompt easier to understand.

Neither of these are necessary for merging though.

**Review by adieyal — APPROVED** [review]

**Comment by akx** [comment]
> * We might want to have an option that converts a variable into an empty string if it isn't defined. Right now it throws an error. That's a good thing, but you might want a more forgiving mode

Yep, that's a comment in the code. I'll implement that as a mode toggle for the sampling context.

> * It would be really useful if we could have variables in the shorthand syntax. We don't need arbitrary expressions but it would be a shame not to be able to do something like this:

Not hard to add! I just wanted some first opinions on this approach. The limitation will then be that the expression can't contain `=` or `)`.

**Comment by akx** [comment]
Heh, `${animal={A|B|C}} __publicprompts/plush-toy(animal=${animal})__` (once implemented) actually causes an infinite recursion, will need to fix that...

**Comment by adieyal** [comment]
Think we're ready to ship? I've been playing around with it for a while now. Parameterised prompts is very cool.

**Comment by akx** [comment]
> Think we're ready to ship? I've been playing around with it for a while now. Parameterised prompts is very cool.

I'd like to make parent-context-referent variable references possible (e.g. `${animal=fox} {${animal=fluffy ${animal} } }`, but that will require an API change for `SamplingContext` (a stack of `variables`). If we can live with that, sure, I think we can ship.

**Comment by akx** [comment]
@adieyal I went ahead and merged this; feel free to bump to 0.21.0 if you want, with the above note about self-referent variables :)

**Pull request merged**
