### PR TITLE
Default wildcards directory

### PR DESCRIPTION
**Pull request by adieyal**
If not provided in the constructor, WildCardManager looks for wildcards in the current working directory

### CODE REVIEW

**Comment by akx** [comment]
🤔 Why was this necessary, though..?

**Comment by adieyal** [comment]
I find that there is some unnecessary boilerplate when setting up DP. Being forced to supply a Wildcard Manager becomes very repetitive.

**Comment by akx** [comment]
@adieyal Alright, I can understand that reasoning. I think we should default to "No directory" though instead of the surprising default of allowing reading any txt file in the working directory..?

**Comment by adieyal** [comment]
What does No directory mean? Does it reject all wildcards?

**Pull request merged**
