### PR TITLE
Rework ActionBuilder/Command/Generator hierarchy

### PR DESCRIPTION
**Pull request by akx**
This does what I threatened to work on in #13, namely reworks the various generator-specific command classes to being just simple dataclasses, and the Generator (which is an unfortunately overloaded name, since there are both PromptGenerators and non-prompt generators, all of which generate prompts nevertheless) classes deal with generating (a possibly infinite) stream of prompts out of them.

### CODE REVIEW

**Comment by akx** [comment]
@adieyal Do you have an idea for a better name for `Generator`s (which aren't `PromptGenerator`s)?

**Comment by adieyal** [comment]
I like what I've seen so far. I'm still reading through it. May only be able to respond fully by tonight though.

**Comment by adieyal** [comment]
Just finished reading it. Very elegant implementation and a pleasure to use.

**Comment by adieyal** [comment]
> @adieyal Do you have an idea for a better name for `Generator`s (which aren't `PromptGenerator`s)?

Thinking about the logic:
1. The prompt template is a string the represents a family of prompts (or even a probabilistic distribution of prompts)
2. The Random/Combinatorial parser generators effectively sample from that distribution
3. MagicPrompt and friends enhance the sampled prompts.

Would it be too obscure to call them samplers? 

Generators is also a valid choice if you think about generating random numbers. In which case the PromptGenerators might need a different name. The idiom composable PromptGenerators composable might also worth considering. Perhaps they might be pipelines, e.g. RandomSampler -> Spellchecking -> MagicPrompt

PromptGenerators don't always encapsulate the samplers. The current JinjaGenerator is an example. We may want to change it in future to make it compatible with the template syntax but right now it doesn't.

**Comment by adieyal** [comment]
I've run some tests with a bunch of prompts using auto1111 and it seems good. Any reason not to publish on pypi?

**Comment by akx** [comment]
@adieyal Let's not publish just yet if that's okay! Samplers sounds alright, I'll do that :)

**Pull request merged**
