### PR TITLE
Fixed wildcards in variants functionality

### PR DESCRIPTION
**Pull request by adieyal**
{2$$__wildcard__} now correctly chooses two values from wildcard.txt

### CODE REVIEW

**Comment by adieyal** [comment]
@akx I would appreciate your thoughts on my approach. 

Firstly in order to handle `{2$$__wildcard__}` I decided to convert it to a proper variant, i.e. `{2$$val1|val2|val3|...}`. I think this is an okay way to do it since it takes advantage of the regular variant machinery. It does get a little confusing when testing since you need to mock the variant rather than the wildcard.

Secondly, to achieve this, I had to remove the min_bound/max_bound manipulation in the dataclasses  and handle it inside the  `_get_variant` methods of the samplers. This gets a little messy. Is there a better way to do it?

**Comment by akx** [comment]
> Firstly in order to handle `{2$$__wildcard__}` I decided to convert it to a proper variant,

Hmm... is that actually necessary? It sounds like we'd just need to evaluate wildcard commands in `combo_to_prompt`? Or am I missing something..?

**Comment by adieyal** [comment]
> > Firstly in order to handle `{2$$__wildcard__}` I decided to convert it to a proper variant,
> 
> Hmm... is that actually necessary? It sounds like we'd just need to evaluate wildcard commands in `combo_to_prompt`? Or am I missing something..?

I'm not following. Are you asking whether the `{2$$__wildcard__}` syntax is necessary, or whether converting the wildcard to a variant is the right way to go?

I don't understand how `combo_to_prompt` will help us here. All the work of unpacking the values from the wildcard and creating candidate pairs still needs to be implemented to be passed to `combo_to_prompt`. In any case, combo_to_prompt is already being used in [combinatorial.py](https://github.com/adieyal/dynamicprompts/blob/main/src/dynamicprompts/samplers/combinatorial.py#L117) by `_get_variant` so it will be used implicitly anyway.

The `{2$$__wildcard__}` is actually a special type of variant syntax where the variant values are stored in the wildcard file. It is different to `{2$$___wildcard__|__wildcard__}`. The latter makes no guarantees about uniqueness, i.e. `{2$$__colours__|__colours__}` could generate `blue,blue` whereas `{2$$__colours__}` won't.

**Comment by akx** [comment]
> I'm not following. Are you asking whether the `{2$$__wildcard__}` syntax is necessary, or whether converting the wildcard to a variant is the right way to go?

Sorry, hadn't had any coffee writing that, it made more sense in my sleepy head. 😁 I mean is conversion (expansion of a wildcard to a variant) necessary, or could we just change how things are evaluated, but maybe not.

Anyway, I'm a bit hesitant about the fact that this is a special case (a single wildcard command within a variant is handled specially; two or more wildcard commands, or a mix of commands, isn't..?) and that changes are needed in so many places?

As for

> I had to remove the min_bound/max_bound manipulation in the dataclasses and handle it inside the _get_variant methods of the samplers. This gets a little messy. Is there a better way to do it?

It seems that the new handling is pretty much 
```
min_bound = min(c.min_bound, len(c.values))
max_bound = min(c.max_bound, len(c.values))
for bound in range(min_bound, max_bound + 1):
```
everywhere; how about refactoring that into a `VariantCommand.adjusted_range(self, n_values)`?

**Comment by adieyal** [comment]
> Anyway, I'm a bit hesitant about the fact that this is a special case (a single wildcard command within a variant is handled specially; two or more wildcard commands, or a mix of commands, isn't..?) and that changes are needed in so many places?

This is old functionality which was broken in the last refactor. It's clearly popular since so many users were anxious to get it back - https://github.com/adieyal/sd-dynamic-prompts/issues/307

Re `VariantCommand.adjusted_range(self, n_values)` do you see that being run in every sampler?  `wildcard_to_variant` already runs adjusts bounds when converting from wildcard to variant. The reason for changing bounds in the `_get_variant` methods is that we need to handle the case for standard variants (rather than wildcard variants). This was previously handled by the `VariantCommand` in [_post_init](https://github.com/adieyal/dynamicprompts/blob/main/src/dynamicprompts/commands/variant_command.py#L28-L34). That is no longer possible since that code is run before we convert from wildcard to variant which means that our bounds will always end up as `min_bound = max_bound = 1`.

**Comment by akx** [comment]
> Re `VariantCommand.adjusted_range(self, n_values)` do you see that being run in every sampler? [...] That is no longer possible since that code is run before we convert from wildcard to variant which means that our bounds will always end up as `min_bound = max_bound = 1`.

I mean it's probably fine to get rid of the code in `_post_init`, but my point was that https://github.com/adieyal/dynamicprompts/pull/54/files#diff-a56350531546a53f0ba9b275c8be7cb725541d8e7b9fc5547391950ec22c5091R132-R137 and 
 https://github.com/adieyal/dynamicprompts/pull/54/files#diff-b30f6b36557f36b6c57337a04eae8a231e52a845119f3c714db8c9a5a40b53f8R74-R79

are effectively the same :)

Anyway, we can refine it later, let's ship this 👍

**Review by akx — APPROVED** [review]

**Comment by Mossbraker** [comment]
I'm using a fresh install of SD, A1111, dynamic prompts, etc. and `{2$$__wildcard__}` still only chooses one value from wildcard.txt. I'm on TheLastBen Colab, in case that's relevant

**Comment by adieyal** [comment]
I think TheLastBen manually installs dynamicprompts. It may be pinned to an old version. Look to see if it's at least 0.21.0

**Comment by Mossbraker** [comment]
Not sure if TheLastBen was pinned to an old version, but it is currently on version 0.21.2 and I'm no longer having the issue I mentioned. Thanks

**Pull request merged**
