### PR TITLE
Have internal sampling APIs return SamplingResults

### PR DESCRIPTION
**Pull request by akx**
This will allow for additional metadata to be gathered during sampling (e.g. wildcard files used, and other future magic).

### CODE REVIEW

**Comment by adieyal** [comment]
Looks good - happy for me to publish a new version?

**Comment by akx** [comment]
This shouldn't change any high-level APIs, so yeah, fine by me :)

Thanks!

**Comment by adieyal** [comment]
@akx, there is a backwards in compatible change in this PR. When updating the dependency in the extension, I get the following:
```shell
  File "./stable-diffusion-webui/extensions/sd-dynamic-prompting/sd_dynamic_prompts/wildcards_tab.py", line 246, in handle_message
    return handle_load_wildcard(event)
  File "./stable-diffusion-webui/extensions/sd-dynamic-prompting/sd_dynamic_prompts/wildcards_tab.py", line 267, in handle_load_wildcard
    values = "\n".join(wf.get_values())
TypeError: sequence item 0: expected str instance, WildcardItem found
```

```shell
> ./stable-diffusion-webui/extensions/sd-dynamic-prompting/sd_dynamic_prompts/wildcards_tab.py(268)handle_load_wildcard()
-> values = "\n".join(wf.get_values())
(Pdb) print(wf.get_values())
[WildcardItem(content='red', weight=99.0), WildcardItem(content='green', weight=1.0)]
(Pdb) print(str(w) for w in wf.get_values())
<generator object <genexpr> at 0x7f14c05f9150>
(Pdb) print(list(str(w) for w in wf.get_values()))
['red', 'green']
```

**Comment by akx** [comment]
@adieyal That's #97, actually, not this one. That's expected though – sddp can just always cast to strings for the tab display IMO :)

**Pull request merged**
